export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_SCORE_START = 'ADD_SCORE_START';
export const ADD_SCORE_SUCCESS = 'ADD_SCORE_SUCCESS';
export const ADD_SCORE_FAIL = 'ADD_SCORE_FAIL';
export const ADD_SCORE_INIT = 'ADD_SCORE_INIT';

export const ADD_GAME_START = 'ADD_GAME_START';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAIL = 'ADD_GAME_FAIL';
export const ADD_GAME_INIT = 'ADD_GAME_INIT';

export const ADD_NEW_PLAYER_START = 'ADD_NEW_PLAYER_START';
export const ADD_NEW_PLAYER_SUCCESS = 'ADD_NEW_PLAYER_SUCCESS';
export const ADD_NEW_PLAYER_FAIL = 'ADD_NEW_PLAYER_FAIL';
export const ADD_NEW_PLAYER_INIT = 'ADD_NEW_PLAYER_INIT';

export const ADD_NEW_TEAM_START = 'ADD_NEW_TEAM_START';
export const ADD_NEW_TEAM_SUCCESS = 'ADD_NEW_TEAM_SUCCESS';
export const ADD_NEW_TEAM_FAIL = 'ADD_NEW_TEAM_FAIL';
export const ADD_NEW_TEAM_INIT = 'ADD_NEW_TEAM_INIT';
export const CANCEL_NEW_TEAM = 'CANCEL_NEW_TEAM';

export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYERS_FAILED = 'FETCH_PLAYERS_FAILED';

export const FETCH_GAMES = 'FETCH_GAMES';
export const FETCH_GAMES_FAILED = 'FETCH_GAMES_FAILED';

export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_TEAMS_FAILED = 'FETCH_TEAMS_FAILED';